### ISSUE TITLE
[BUG] Window becomes unresponsive under certain conditions

### ISSUE THREAD

**Issue by anthonyronda** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#41] opened 2021-06-04 20:40 UTC
Please follow up with Discord user RautenRonny#5980, or I can follow up with them on your behalf

**Module Version:** v0.6.0

**Describe the bug**

Quest will become unresponsive and after closing the Quest Log completely lost if:
•    picture added to “Quest Description”
•    item (some items like wand of the warmage+1) dragged to “Rewards”; other items like Amulet of Health is fine

**To Reproduce**
1. Have an open quest
2. Add a picture to the Quest Description
3. Add Wand of the Warmage+1 to the Quest (some other items also affected)

**Expected behavior**
The quest continues to function, no errors or instability

**Browser:**
Chrome (latest as of June 2021)

**Foundry Version:** 
0.8.6

**Game System:** 
dnd5e

**Comment by typhonrt** [comment] 2021-06-12 07:25
I can't reproduce this issue w/ the latest unreleased version of FQL which has some major fixes in general. Added many items to quest rewards including the ones mentioned and things work fine. 

There is a possibility that the issues fixed in the upcoming release address this issue, but again can't reproduce w/ the latest unreleased FQL.

**Comment by typhonrt** [comment] 2021-06-19 01:09
I'm going to close this issue as the forthcoming release of FQL is super efficient. Everything works by storing UUIDs and is well tested. The previous FQL version had issues w/ storing full data for actors and items in the quest data.  If by chance you notice an issue with the latest FQL coming out shortly please do reopen and I'll take a look.

**Closed by typhonrt** 2021-06-19 01:09 UTC
Labels: bug
