### ISSUE TITLE
v12 support [Beta Version Available]

### ISSUE THREAD

**Issue by kristkos** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#44] opened 2024-05-29 02:17 UTC
Title says it all.

**Comment by AvDalfsen** [comment] 2024-06-02 08:58
Seconded. It's the only reason I'm still using V11.

**Comment by geatancasegrain** [comment] 2024-06-03 02:14
+1 , adding my voice to fix this fantastic must have add-on .

**Comment by typhonrt** [comment] 2024-06-03 02:23
I'll be working on the v11 / v12 dual compatibility release this week. 

Beside v12 support some small quality of life enhancements I'm going to investigate adding are:
- Allow actor documents to be set as rewards. Item Piles and game system loot chests are often implemented as actors. This will allow game system specific distribution of currency / XP. 
- Enrich the text of custom rewards. A fair amount of game systems 
- Verify linking Monk's Enhanced Journal entries as quest givers / make sure images display.

**Comment by Cedric-the-Destroyer** [comment] 2024-06-10 18:22
Super awesome, and I am thrilled it is still being actively updated. As dead as the other one was (which makes sense as it isn't the projects home) I was afraid it was an abandoned project. I only recently found it and started using it.

**Comment by Seff55** [comment] 2024-06-12 15:18
Thank you so much. My quest log vanished and I panicked a bit as I realised a lot was in there. Luckily the once a week game doesn't mean it's super essential but would love to see it in v12 as it's a massive boon to my players to not only track all the things they have done in this game but have a clear choice of quests to pick up when they aren't sure what to do. Really easy system to use as well.

**Comment by typhonrt** [comment] 2024-06-15 04:38
> One of the most useful and phenomenal modules for any given system - would love to see it updated to V12 - thanks for all of it so far! I'll have to port to the raw journals for now, so you can bet I'll be cheering on the process. Good luck!

Or you can wait until Sunday or Monday when things are likely to be released.

**Comment by AvDalfsen** [comment] 2024-06-15 07:50
> > > One of the most useful and phenomenal modules for any given system - would love to see it updated to V12 - thanks for all of it so far! I'll have to port to the raw journals for now, so you can bet I'll be cheering on the process. Good luck!
> > 
> > 
> > Or you can wait until Sunday or Monday when things are likely to be released.
> 
> To be honest, I first saw the developer comment that it would be worked on 'this week' and it's been two, edging on three since. I want to show positivity and faith, not try to rush, and I am cheering them on.
> 
> I know how unexpected developments can slow these things down. If they didn't get it released in the time they thought, chances are it may not be this week, or the next, and that's totally fine. I just want them to know people are definitely looking forward to it, and will be grateful for the hard work done.
> 
> Edit: I also don't want to assume you are the sole developer, or anything, but if this is your own update on an actual ETA, then that's good. I tend to run my sessions on Monday evenings, so it'd be pretty neato.

From personal experience: don't update to a new version of Foundry the day of/before a session 😬 

Anyhow, many thanks for your work, @typhonrt. Looking forward to the release :)

**Comment by kristkos** [comment] 2024-06-17 22:42
I didn't expect to start an overall chain. 
But thank you so much for the extensive work put into it!

**Comment by Rencos1** [comment] 2024-06-18 15:17
Until the issue is fixed officially, it can be fixed very easily. Just replace all references to CONST.DOCUMENT_PERMISSION_LEVELS by CONST.DOCUMENT_OWNERSHIP_LEVELS in dbSchema_1.js, Utils.js, Quest.js and QuestDB.js.

**Comment by typhonrt** [comment] 2024-06-18 22:23
> Until the issue is fixed officially, it can be fixed very easily. Just replace all references to CONST.DOCUMENT_PERMISSION_LEVELS by CONST.DOCUMENT_OWNERSHIP_LEVELS in dbSchema_1.js, Utils.js, Quest.js and QuestDB.js.

Folks are certainly free to make this general patch locally albeit not convenient for most.

This only fixes the immediate runtime issue on v12, but does not address a thorough maintenance review of FQL as a whole. To keep FQL in tip top shape I need to do a thorough review / testing cycle of all functionality for the v12 release. I did not have time to do that for the v11 release. There are other subtle issues that need to also be addressed. I already got started on this process, but an example is that when you create a new quest the default permissions / ownership for all players is not set properly and likely didn't work as intended during the whole v11 timeframe yet no one really reported a problem. [In the code at this location](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/master/src/control/QuestDB.js#L355) `permission` needs to be `ownership`. This doesn't crash FQL, but it doesn't set the default ownership level of new quests created. This is not something that is caught without examining the functionality of FQL as a whole. I don't use FQL on a day to day basis or run any Foundry campaigns currently. The only time I take a look at FQL is during the update process when a new core version is released.

I can launch into a diatribe about the state of Foundry for 3rd party developers and needless to say I'll skip it, but things are not good all around. I'm a professional developer who spent _a lot_ of my own money, much more than you'd expect anyone to sanely do so, developing FQL and my larger aspirations about doing sustainable pro-grade 3rd party package dev beyond FQL _is not_ materializing and likely it won't. 

Currently, I am engaged and have been for the last ~4 weeks in a massive modernization PR to a highly used math library [gl-matrix](https://www.npmjs.com/package/gl-matrix). This library averages ~1.8MM weekly downloads, so is not small change. I utilize `gl-matrix` in my larger Svelte based framework for Foundry that many other devs use to create awesome engaging packages that you use. Due to the time sensitive and momentum requirements to get this PR accepted, which it will because I have put in the work, I have to see that through before I can work on FQL. It's at that last ~3% stage, but as things go with professional grade development that last final finishing aspect can take additional time.

Mind you that this same professional high quality eye for detail and finishing capability is what is going to be applied to the v12 FQL release, but it needs to wait in the queue and is next up.

**Comment by typhonrt** [comment] 2024-06-19 00:43
And when I said "wait until Sunday or Monday when things are likely to be released" that was accurate at that time where I even got half a day in on starting (Friday). However, there were further unexpected developments Friday afternoon regarding the `gl-matrix` work and that simply takes priority until that is handled. It looks like that is wrapping up where there is a breaking point in the next couple of days and if all goes well FQL is out this weekend... Don't quote on that though, but likely.

There are no outstanding bugs with FQL and it's been bug free for ~2 years. Small things like the very minor document ownership thing with a new quest are only detectable for the most part if you know exactly how FQL should work. The average user would experience nothing breaking, but not know what the intended behavior is like. _If_ it was broken during v11 no one reported it.

Another minor complication that is a bit of a PITA is that I don't own the Foundry package manager rights to update FQL. Super weird and odd, but I have to track down someone else to update it and it's a PITA, so I'd rather just do that once. Even if FQL is wrapped up for release that can take an extra day or two for the update to post.

**Comment by typhonrt** [comment] 2024-06-19 01:26
> I didn't notice any beaks in V11, personally, and I do remember actively changing it so people by default couldn't see new quests, and it working, so it may well have been working for most of V11 or an edge-case. That, or perhaps it really is just that subtle.

Quite possibly just a v12 thing, but something that is non-obvious I noticed relatively quickly. What I was pointing out is that the basic CONST reference fix gets things working, but doesn't take into account other subtle aspects that are non-breaking that v12 might have messed with. The CONST thing would have been caught in the v11 update, but since I did a quick pass then and it doesn't generate deprecation warnings it slipped through as v11 worked. For the most part as long as there isn't a huge document model change like in `0.8` and `v10` things should continue to work fine. 

Also good news for the P2FE folks as they just posted today that the v12 system release should take into account this recent issue #39, so hopefully that is verified / enabled. 

When I mention doing a full end to end testing regimen when available on a new core release I test across the top 30 game systems. I also test every feature and it takes time given the client / server / multiple players aspect of FQL. FQL appears reactive, but it is a whole lot of plumbing under the hood to give that appearance. It's been a while for that, so this is part of the process this time around and takes ~6 hours just for detailed manual testing of FQL. This new release will also work on v11 / v12, so I have to test on both core releases.

**Comment by ThingsCouldGetDicey** [comment] 2024-06-19 23:04
im really happy my inline checks is being added or working. thanks!

**Comment by typhonrt** [comment] 2024-06-19 23:22
> im really happy my inline checks is being added or working. thanks!

It's not something specifically I've implemented. This is only for PF2E as they are overriding core Foundry functionality to make it work. Also, I'll be verifying this against the unreleased v12 version of PF2E, but at least can give feedback to the system maintainers if their solution works. Indeed for other game systems it's going to be hit or miss and it's not likely other system maintainers will patch Foundry core to enable this kind of thing. A good issue / request for Foundry v13 though is making this easier for system developers to implement said features in a reliable and standardized manner.

So hopefully it does work for PF2E and I can confirm it in FQL.

**Comment by ThingsCouldGetDicey** [comment] 2024-06-19 23:30
> > im really happy my inline checks is being added or working. thanks!
> 
> It's not something specifically I've implemented. This is only for PF2E as they are overriding core Foundry functionality to make it work. Also, I'll be verifying this against the unreleased v12 version of PF2E, but at least can give feedback to the system maintainers if their solution works. Indeed for other game systems it's going to be hit or miss and it's not likely other system maintainers will patch Foundry core to enable this kind of thing. A good issue / request for Foundry v13 though is making this easier for system developers to implement said features in a reliable and standardized manner.
> 
> So hopefully it does work for PF2E and I can confirm it in FQL.

when you say unreleased do you mean on a branch that is beta or something thats being worked upon? currently the v12 version of pf2e is out https://github.com/foundryvtt/pf2e/releases/tag/6.0.3

**Comment by threes-and-sevens** [comment] 2024-06-19 23:33
I'll add my gratitude to your hard work on this, @typhonrt. 

Like all labour-of-love modules, I'll take anything I can get with heartfelt thanks : )

**Comment by typhonrt** [comment] 2024-06-20 06:57
> > > im really happy my inline checks is being added or working. thanks!
> > 
> > So hopefully it does work for PF2E and I can confirm it in FQL.
> 
> when you say unreleased do you mean on a branch that is beta or something thats being worked upon? currently the v12 version of pf2e is out https://github.com/foundryvtt/pf2e/releases/tag/6.0.3

This commit in PF2E from a day ago:
https://github.com/foundryvtt/pf2e/commit/7edaa67b3834aff685569bbb31ad2a2f625ad860

`6.0.3` is 2 days old.

**Comment by typhonrt** [comment] 2024-06-25 23:21
Just letting folks know that I've wrapped up my other work and I'll be starting on FQL in earnest tomorrow (Wed) until it is released. No chance for further delay. As I mentioned this time around it's a full in-depth analysis of the code base and testing cycle in addition to adding / verifying a few new features. I appreciate everyone's patience as it's not always going to be the case where the Foundry release cycle will match any given 3rd party developers schedule or commitments.

The v12 FQL release will continue the high quality / bug free experience and if things work out how I hope for the new features added things will be rather nice moving forward.

**Comment by ThingsCouldGetDicey** [comment] 2024-07-04 17:43
just wanted to ask if there was an eta on this as its the last mod i need before switching my kingmaker game over. no rush or anything just wanted to know a reasonable timeframe. :)

**Comment by typhonrt** [comment] 2024-07-04 20:31
@ThingsCouldGetDicey et al

There is a public beta release available of the next FQL release (`0.8.0-beta.1`). It is v11 / v12 capable and is fully functional. 

Check out this video for install and quick overview of new features:
https://www.youtube.com/watch?v=cX8EbdRLJe8

I'll be making an actual release video for the public release later.

To install the beta release:

- Uninstall any existing FQL module.

- Install the beta from this package link in the Foundry package manager:
`https://github.com/typhonjs-fvtt-scratch/foundryvtt-forien-quest-log/releases/latest/download/module.json`

For good measure when the official `0.8.0` release becomes available uninstall the beta release and reinstall FQL from the Foundry package manager.

--- 

There are no DB changes / migrations so this is a safe update. As always though please back up your data. 

New features:
- Actor documents can be set as rewards (Item Piles / PF2e loot actors)
- All rewards can have associated image changed.
- Player notes

If you are using `dnd5e` you can use the system text enrichment capabilities to create a custom reward using:
`[[/award 1000xp]]` to distribute XP.

---

The official release may happen next week. Do remember to uninstall the beta and re-install the official release as the beta repo / resources will be taken down after the official release is available.

**Comment by ThingsCouldGetDicey** [comment] 2024-07-04 20:35
> @ThingsCouldGetDicey et al
> 
> There is a public beta release available of the next FQL release (`0.8.0-beta.1`). It is v11 / v12 capable and is fully functional.
> 
> Check out this video for install and quick overview of new features: https://www.youtube.com/watch?v=cX8EbdRLJe8
> 
> I'll be making an actual release video for the public release later.
> 
> To install the beta release:
> 
>     * Uninstall any existing FQL module.
> 
>     * Install the beta from this package link in the Foundry package manager:
>       `https://github.com/typhonjs-fvtt-scratch/foundryvtt-forien-quest-log/releases/latest/download/module.json`
> 
> 
> For good measure when the official `0.8.0` release becomes available uninstall the beta release and reinstall FQL from the Foundry package manager.
> 
>     * Optional: Install latest `Item Piles / 3.0.5` if your system is supported.
> 
> 
> There are no DB changes / migrations so this is a safe update. As always though please back up your data.
> 
> New features:
> 
>     * Actor documents can be set as rewards (Item Piles / PF2e loot actors)
> 
>     * All rewards can have associated image changed.
> 
>     * Player notes
> 
> 
> If you are using `dnd5e` you can use the system text enrichment capabilities to create a custom reward using: `[[/award 1000xp]]` to distribute XP.
> 
> The official release may happen next week. Do remember to uninstall the beta and re-install the official release as the beta repo / resources will be taken down after the official release is available.

if i uninstall it will it delete any of the quests outstanding or made?

**Comment by typhonrt** [comment] 2024-07-04 20:39
> if i uninstall it will it delete any of the quests outstanding or made?

No... Quests are stored as journal documents. Always back up your data though regardless especially when moving to a new Foundry core version.

**Comment by Tridus** [comment] 2024-07-05 01:38
Tried it out in my game tonight and it's working well. Didn't encounter any issues creating quests.

**Comment by typhonrt** [comment] 2024-07-14 23:22
So, a small update on progress and what is going on... 

If all goes well there _should_ be an official release this week. It's taken longer because I've decided to return FQL to Forien, the original developer. He stepped away at the end of '20 from Foundry dev, but has been back for the last year or so. In this process I've taken extra time to thoroughly go through the codebase modernizing / streamlining it with today's knowledge / ES2022. A lot of the code for FQL was done in '21, so even a 3 year gap can lead to better coding standards.

I estimated the cost for me to do the next wave of significant maintenance in moving to the new "AppV2" UI API and all that entails to cost me at least $10k USD. I can no longer stomach such losses for the actual real work involved. This is not work that needs to be done immediately, but something in the next 1-2 years. 

I'm passing back the torch to Forien with FQL in a strong position to continue forward. New features in this upcoming release bring several new possibilities for a complete questing solution particularly around XP / currency / item distribution.

The final timing snag will be the package transfer and final release process getting Forien back in control of the package listing. The Leagues source repo where FQL has been developed will be moving back upstream to Forien's original repo.

So it's happening, but extra parts of the process this time around. There is a beta release available above for now.

**Comment by typhonrt** [comment] 2024-07-18 20:21
This fork is now merged upstream to Forien's original repo. An email for the package transfer back to Forien is pending. It's up to Forien to list / publish the next release. I don't know when that might occur, but hopefully soon.

**Comment by typhonrt** [comment] 2024-07-26 21:49
Yesterday or so FQL has now been officially released on the Foundry package manager. Please note that anyone that installed the beta release described above should uninstall FQL and reinstall from the Foundry package manager to ensure that you continue to get updates. 

All future development of FQL will be in Forien's hands again, so refer to the main repo for issues. When I started working on FQL it was in serious disrepair / MVP status with Foundry `v0.8` tanking it entirely. With the `0.8.0` release I cleaned up / streamlined the codebase and returned it to Forien in a bug free state. While he will have to understand the codebase to move forward FQL is in a sound state for now.

**Closed by typhonrt** 2024-07-26 21:49 UTC
Labels: enhancement
