### ISSUE TITLE
[BUG] Locks up Foundry if enabled on 0.8.6

### ISSUE THREAD

**Issue by Hydrall** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#33] opened 2021-05-31 19:23 UTC
**Module Version:** v0.5.4

**Describe the bug**
If enabled, Forien's Quest Log causes foundry to no longer finish loading. A grey screen is all that appears.
The only error I noticed:
```
Uncaught (in promise) Error: Missing Document initialization type!
    at Game.initializeEntities (foundry.js:4315)
    at Game.setupGame (foundry.js:4285)
    at async Game._initializeGameView (foundry.js:5114)
```

**To Reproduce**
Create a world or load one, then activate the module.

**Screenshots**

![image](https://user-images.githubusercontent.com/14931056/120233550-1319c800-c224-11eb-878d-6d0eec5da17d.png)

**Browser:**
 - Foundry's default app.

**Foundry Version:** 0.8.6

**Game System:** DnD5e

**Comment by RinVindor** [comment] 2021-05-31 21:33
Yeah getting the same issue.

**Comment by xdy** [comment] 2021-05-31 22:00
Duplicate of #13 
I got a partial fix from Eadorin earlier today, after some more work only the menu on the left doesn't work, so I've disabled it for now (FQL can still be reached from the Journal tab on the right).
Will *probably* do a release tomorrow.

**Closed by xdy** 2021-05-31 22:00 UTC
Labels: bug
