### ISSUE TITLE
Save Quest description after modification

### ISSUE THREAD

**Issue by Turqueso** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#24] opened 2021-05-09 19:35 UTC
**Module Version:** v0.5.7

**Describe the bug**
After you create a quest and you  try to modify the quest description, it doesn't saves changes

**To Reproduce**
1. create quest
2. Close and open it
3. change quest description
4. close and open the same quest
5. Changes were not saved

**Expected behavior**
It should save the changes to que descripton
 - 

**Foundry Version:** 0.7.9

**Game System:** dnd5e

**Comment by Turqueso** [comment] 2021-05-11 16:26
Recently found out there's a save button on the format bar, but since foundry save everything automatically it would be nice if the module would do the same

**Comment by anthonyronda** [comment] 2021-06-12 19:25
Thanks for submitting an issue. I'm noting after your comment reply that this is an enhancement request, and not a bug report. I'll let other contributors chime in on this request

**Comment by typhonrt** [comment] 2021-06-19 02:00
Good news.. The new version of FQL 0.7.0 which about to be released saves any open text editing fields when closing the dialog. So great enhancement idea. It was a bit tricky to pull off, but I got it in the new upcoming release.

**Closed by typhonrt** 2021-06-19 02:00 UTC
Labels: enhancement
