### ISSUE TITLE
[BUG] Quests copied from browser with returns fails

### ISSUE THREAD

**Issue by whelan** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#32] opened 2021-05-28 20:30 UTC
**Describe the bug**
IT seems that after I edited the quest log after upgrading from 0.7.9 to 0.7.10. The module stopped working. I can not even after deleting all quests get it back to the normal view. It just show it like a journal folder.

**Comment by xdy** [comment] 2021-05-31 22:02
Hmm. I just tried it on 0.7.10 (windows, foundry client, dnd 1.2.4) and it works for me.
Do you get any exceptions in the console?

**Comment by whelan** [comment] 2021-06-01 06:55
Hmm, strange I got it to work again, by deleting all info and tried to create the quest logs again. I think it could be some character parsing. The behavior I have experienced is that I edit a quest and all of a sudden it will not render any quests, as active or in the quest log interface. 

I will see if I can reproduce it again in another world on my foundry server.

**Comment by xdy** [comment] 2021-06-01 15:17
If it happens again you can always get the raw text out of the quest by turning on the module setting to show the _fql_quests folder, open the journal entry for the quest and copying the text. Which at least mitigates it a bit if it happens again.

**Comment by whelan** [comment] 2021-06-02 12:15
This was as I suspected another problem. I found that if you copy some text from a browser and paste it into the quest log. It will translate new paragraphs to \n and that results in a Json parsing error with \n. 

Used the quest log to handle HotDQ quests.

**Comment by Bltgn** [comment] 2021-06-08 15:13
Hello, I encountered a similar error after pasting test from a word processor that replace single quotes with apostrophes. Other extended characters might possibly break Json parsing.

To reproduce, create a quest, and paste the following line in the description (note the non standard quote):
> The broken text de l’enfer.

The quest log will not appear anywhere and the error will be visible in the logs. If that happen in a sub-quest, the entire quest window will not open again until all the quest and sub-quests are deleted.

**Comment by xdy** [comment] 2021-06-10 17:52
This should be fixed once #45 (courtesy of @typhonrt) has been merged (it *may* result in old broken quests staying broken, though I think most of those can be opened with this fix.)

**Comment by typhonrt** [comment] 2021-06-19 01:58
This is definitely fixed in the new version.. Incidentally 0.8.7 might have the old FQL springing back to life... A little at least. The server side content filtering doesn't seem to overly break things. The new version is considerably more flexible in many ways.. Just a few more days.. But I'm going to close this issue. Please feel free to reopen if the next version of FQL doesn't work for you.

**Closed by typhonrt** 2021-06-19 01:58 UTC
Labels: bug
