### ISSUE TITLE
[BUG] adding quest entity link to a journal entry prevents the journal entry from being opened.

### ISSUE THREAD

**Issue by ofdiceandmagic** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#48] opened 2021-06-15 12:58 UTC
**Module Version:** v0.6.0

**Describe the bug**
Adding a quest entity link to a journal entry prevents the journal entry from being opened.

**To Reproduce**
1. Copy quest entity link from the quest
2. Paste it into a journal entry
3. save the entry
4. try to open it again

**Expected behavior**
Journal entries should open even with quest entity links.

**Browser:**
 - Chrome

**Foundry Version:** 
0.8.6

**Game System:** 
DND 5e

**Additional context**
This issue is reproducible without any other modules enabled.

**Comment by scooper4711** [comment] 2021-06-15 14:49
Duplicate of #46

**Comment by typhonrt** [comment] 2021-06-15 21:34
Also this is fixed in the forthcoming release of FQL this week. I'll be closing out all the issues in the tracker hopefully before the release. This was actually broken due to the 0.8.x switch.

**Closed** 2021-06-19 00:11 UTC
Labels: bug
