### ISSUE TITLE
Double the max length of abstract reward text entry from 48 to 96 characters.

### ISSUE THREAD

**Issue by pho3bus** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#106] opened 2021-07-23 18:52 UTC
In one of the recent releases (past week or two), the "Add Abstract" text field does not allow more than 48 characters:
![image](https://user-images.githubusercontent.com/48997811/126827990-5ffcd9a2-8c57-4df8-83dd-3514ecf5fa75.png)

Tested in module version 0.7.5, Forge version 0.8.8 using Chrome Version 91.0.4472.164.

**Comment by typhonrt** [comment] 2021-07-23 18:57
This by design to not overflow a single line of text.

**Comment by pho3bus** [comment] 2021-07-23 19:40
Is this a recent change? I have Abstracts that I created a couple weeks ago that are much longer:
![image](https://user-images.githubusercontent.com/48997811/126833039-6036632d-df80-4b24-a68d-d615e8c7fb86.png)

I find it helpful to have longer descriptions when describing unidentified magic items.

**Comment by typhonrt** [comment] 2021-07-23 19:45
This is a recent change. There was no max before. You could also overrun the GUI and do all sorts of nasty UI flaws in display w/ extra long text. 

You certainly posted a reasonable use case. I do want to limit it to 96 characters or two lines of text max.

**Comment by pho3bus** [comment] 2021-07-23 19:46
I think two lines would be perfect, thanks! I appreciate your flexibility.

**Comment by typhonrt** [comment] 2021-07-23 19:52
Could you possibly review some of the other text input areas.  Here are the current limits:
- quest name (48 characters) - IMHO this really needs to be this length
- custom quest giver (24 characters) - Again can cause issues especially w/ future planned space for new features.

These two I'm more leaning towards not changing as it will impact the space reserved for future features.

**Comment by pho3bus** [comment] 2021-07-23 20:01
The longest quest name I have currently is 56 characters ("Protect Phandalin and the Surrounding Area from Cryovain"), but I think 48 is reasonable.

24 characters for custom quest giver also seems reasonable--for me, this is usually just an NPCs name, typically 15 characters or less.

**Comment by typhonrt** [comment] 2021-07-23 20:06
Cool yeah.. There are soon going to be several more options like inputting location, priority, type of quest, along with potential open user tagging. If you are on a 4K monitor expanding the default size of the windows is easy, but I'm definitely concerned on expanding the default size for 1080P resolution, so space is at a premium. The abstract rewards change will drop on `0.7.6`. It's a simple change. Thanks for your feedback!

**Comment by typhonrt** [comment] 2021-07-23 20:13
Just some implementation notes if the RCOS team is around to handle this issue.. 

Change `maxlength="48"` to `maxlength=96` in `HandleDetails.rewardAbstractEditName` and `HandleDetails.rewardAddAbstract`

`./src/view/preview/HandleDetails.js`

**Comment by typhonrt** [comment] 2021-08-07 16:39
Released with `0.7.6` which is available now.

**Closed by typhonrt** 2021-08-07 16:39 UTC
Labels: enhancement
