### ISSUE TITLE
Can't open quest log window

### ISSUE THREAD

**Issue by Shayulghul** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#18] opened 2021-04-04 18:56 UTC
**Module Version:** v0.5.4

**Describe the bug**
After updating to v0.5.4, Forien's Quest Log no longer opens for me.

**To Reproduce**
1. Start world.
2. Click the Quest Log button in the Journal pane of the sidebar on the right.
3. Nothing happens.

**Expected behavior**
The quest log window should open.

**Screenshots**
N/A

**Browser:**
Chrome Version 89.0.4389.114

**Foundry Version:** 
v.0.7.9

**Game System:** 
D&D 5e

**Additional context**
- My quests are still there when I view the debugging folder.
- Console says, "Error: An error occurred while rendering QuestLog 3: The partial modules/forien-quest-log/templates/partials/quest-log/tab.html could not be found"

**Comment by xdy** [comment] 2021-04-05 09:57
Closing this issue as it's a duplicate of #17, see that issue.

**Closed by xdy** 2021-04-05 09:57 UTC
Labels: bug
