### ISSUE TITLE
[BUG] Questtracker cuts off objective title

### ISSUE THREAD

**Issue by gsterling** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#31] opened 2023-04-07 20:10 UTC
**Module Version:** v0.7.11

**Describe the bug**
When creating an objective with more than 2 words, it will get cut off in the quest tracker. I think the problem is, that the quest tracker converts each space into a newline. This only happens for objectives yet to be completed. Completed objectives are shown as expected.

**To Reproduce**
1. Create new quest
1. Create an objective called "Objective with a really long title"
1. Activate the quest
1. Open quest tracker
1. Click on the active quest
1. See cut off objective (Screenshots below)

**Expected behavior**
Show the complete objective title in the quest tracker for all non-completed quests.

**Screenshots**
Quest with long objective
![image](https://user-images.githubusercontent.com/58980630/230671709-d8047217-e8a2-4632-91c6-1927ce6c0ca9.png)

Completed quest
![image](https://user-images.githubusercontent.com/58980630/230671740-aaf94103-978c-4a36-9423-2f1b5c042bbd.png)

Another quest with a minimal 3 word objective
![image](https://user-images.githubusercontent.com/58980630/230672127-32f05709-5a99-4a0f-9b7b-c8eb5798ebcd.png)

**Browser:**
 - Foundry NodeJS-Standalone

**Foundry Version:** v10.291

**Game System:** [Splittermond](https://foundryvtt.com/packages/splittermond)

**Comment by typhonrt** [comment] 2023-04-07 21:20
Quite likely this is a CSS conflict with the game system or another module. Can you try disabling all modules and check again. Then try another game system like `dnd5e` and check again. If this was a common occurrence I would have known about it before now. There was recently reported another game system that also improperly scoped its CSS / styles which you can read about here: #30.

**Comment by typhonrt** [comment] 2023-04-07 21:56
I did detect some potential style conflicts with the game system, but this seems to be a conflict with another module that you are using. FQL scopes its styles appropriately, but not all other Foundry packages may use good practices. Since it is not the game system at fault per se you'll just have to work through the modules you have enabled to figure out which one is misbehaving. Once you find it feel free to post a message here and I'll create an issue on the offending modules repository to make a note of the conflict. 

Here is a pict when I have Splittermond loaded and really long quest objectives:
<img width="1014" alt="Screen Shot 2023-04-07 at 2 52 08 PM" src="https://user-images.githubusercontent.com/311473/230683730-c85d7e48-487b-4474-8565-318d8def0cf8.png">

**Comment by gsterling** [comment] 2023-04-08 10:02
Oh yeah. Sorry for not testing all modules earlier.

The culprit is [JTCS - Art Gallery](https://foundryvtt.com/packages/journal-to-canvas-slideshow/).

It does add buttons on the lower left of documents, that maybe interfere here:
![image](https://user-images.githubusercontent.com/58980630/230715372-8be31c99-b2e7-4774-88dc-b03692603a7c.png)

Can you still fix it, since it works for completed objectives or should I contact the creator of JTCS?

**Comment by typhonrt** [comment] 2023-04-08 10:54
HI @gsterling. I have opened an issue with the JCTS module. Looking through the issues in that repository there are several other clashes with other modules and possibly even game systems. It indeed is an issue that JCTS needs to fix and not FQL. As things go the JCTS module uses many non-specific CSS class names that can easily override or conflict with properly scoped CSS. A bit more details on the specific conflicting CSS rule from JCTS is in this issue which you can subscribe to for any updates when JCTS makes them.

https://github.com/Evannessa/Journal-To-Canvas-Slideshow/issues/48

I'm going to close this issue as `won't fix` as the problem is not with FQL.

**Closed by typhonrt** 2023-04-08 10:54 UTC
Labels: wontfix
