### ISSUE TITLE
[BUG] Cannot create a new quest

### ISSUE THREAD

**Issue by Bryn1701** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#47] opened 2021-06-12 13:58 UTC
**Module Version:** v0.6.0

**Describe the bug**
When I try to create a new quest, I click either the save button or the add new quest button and both methods make the input blank and throws up the following errors(See attachment)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Quest Log'
2. Click on 'Add new Quest'
3. Add new quest title and add image and input quest description.'
4. Either click the save button or add to quest log and watch it vanish.

**Expected behaviour**
I expect it to go to the next screen so I can add the quest rewards etc.

**Browser:**
 Chrome version 91.4.4472

**Foundry Version:** 
0.8.6

**Game System:** 
D&D 5e 1.3.3
[Quest Log Error.txt](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/files/6642294/Quest.Log.Error.txt)

**Comment by xdy** [comment] 2021-06-12 15:28
This bug will be fixed with the next release. Until then it *might* work if you make sure the quest title and description only contains ascii text (e.g A-Za-z0-9).
Closing as duplicate of #32

**Closed by xdy** 2021-06-12 15:28 UTC
Labels: bug
