### ISSUE TITLE
[BUG] Can't add actor to quest

### ISSUE THREAD

**Issue by JJBocanegra** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#49] opened 2021-06-19 20:14 UTC
**Module Version:** v0.6.0

**Describe the bug**
When creating a quest, it allows to drag an actor to the quest, but when you finish creating it, the actor is missing. It also doesn't allows to edit an actor.

**To Reproduce**
1. Click on create new quest
2. Drag and drop an actor to the square on the far top left corner
3. Give the quest a name
4. Press on "Create"
5. Check that the created quest does not have the actor

**Expected behavior**
When you add an actor to a quest, the actor should be there after creating it.

**Foundry Version:** 0.8.7

**Game System:** D&D5e

**Additional context**
In the console I can see this warnings:
```
foundry.js:9736 The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0
```

**Comment by bobziemerman** [comment] 2021-06-19 20:46
I'm seeing this as well; they just closed another ticket for this yesterday saying that it will be fixed in the new release that's supposed to go out soon

**Comment by typhonrt** [comment] 2021-06-19 21:07
Yes this is a duplicate of several other issues. Please be patient as a significantly improved FQL is due to be released momentarily.

**Closed by typhonrt** 2021-06-19 21:07 UTC
Labels: bug

**Comment by JJBocanegra** [comment] 2021-06-19 21:14
It's better to leave it open until the release, to avoid duplication, maybe
tag it with "implemented in next version" for everyone to see.
