### ISSUE TITLE
[BUG] - In Progress Quests have vanished after trying to edit one

### ISSUE THREAD

**Issue by happydevil37** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#40] opened 2021-06-02 23:10 UTC
**Module Version:** v0.6.0

**Describe the bug**
All Active and In progress quests have vanished after upgrading to 0.6 and Foundry 0.8.6

**To Reproduce**
1. Go toIn progress quests
2. Click on Edit, or add new
3. See error

SyntaxError: Unexpected token \ in JSON at position 85
    at JSON.parse (&lt;anonymous&gt;)
    at Function.getContent  (guest.mjs:410)
    at guest.mjs:438
    at Array.forEach (<anonymous>)
    at Function.getQuests (quest.mjs:437)
    at QuestLog.getData (quest-log.mjs:47)
    at QuestLog._render (foundry.js:2041)
    at z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:448)
    at QuestLog.🎁Application.prototype._render#lib-wrapper (libWrapper-errors.js:268)
    at QuestLog.🎁Application.prototype._render#0 (libWrapper-wrapper.js:142)
Forien's Quest Log | Quest Folder contains invalid entry. The "Xulgaths in the Tower" is either corrupted Quest Entry, or non-Quest Journal Entry.

**Expected behavior**
active quests should appear and should be able to create new ones.  Have tried disabling the module and re-enabling

**Foundry Version:** 
0.8.6
**Game System:** 
pf1, pf2e
**Additional context**

**Comment by xdy** [comment] 2021-06-04 02:19
The problem is that the quest contains a character the json parser can't handle properly.
The only way I know to get around this is to enable the "Show Quest Folder" setting, go into the _fql_quests folder that then becomes visible, copy the text from the journal, disable the setting, delete the quest and recreate it.
You *might* be able to *carefully* edit out the offending character from the quest when you open it as per above, if you can figure out which character it is, but I haven't actually tried it.
In my case it was an errant "\n" that had been pasted into the quest.

**Comment by happydevil37** [comment] 2021-06-04 02:43
Sorry but that didn’t work….

 

I deleted everything and still can’t add a new quest…

 

A new error has shown up tho… which might be useful ?

 

foundry.js:3262 You are referencing DocumentSheet#entity which has been deprecated in favor of DocumentSheet#document

get entity @ foundry.js:3262

foundry.js:2032 Foundry VTT | Rendering ImageHoverHUD

foundry.js:2005 ReferenceError: An error occurred while rendering ImageHoverHUD 88: DEFAULT_TOKEN is not defined

    at ImageHoverHUD.getData (image-hover.js:74)

    at ImageHoverHUD._render (foundry.js:2041)

    at z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:448)

    at ImageHoverHUD.🎁Application.prototype._render#lib-wrapper (libWrapper-errors.js:268)

    at ImageHoverHUD.🎁Application.prototype._render#0 (libWrapper-wrapper.js:142)

    at ImageHoverHUD._render (foundry.js:28153)

    at ImageHoverHUD.render (foundry.js:2003)

    at ImageHoverHUD.bind (foundry.js:28128)

    at ImageHoverHUD.showArtworkRequirements (image-hover.js:243)

    at image-hover.js:303

(anonymous) @ foundry.js:2005

foundry.js:9717 The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0

get _id @ foundry.js:9717

backend.mjs:306 Foundry VTT | Created JournalEntry with id [CjSyHPNCdFYbRdxj]

3foundry.js:9717 The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0

get _id @ foundry.js:9717

foundry.js:9735 The Document#entity property has been deprecated in favor of Document#documentName. Support will be removed in 0.9.0

get entity @ foundry.js:9735

foundry.js:2032 Foundry VTT | Rendering JournalSheet

foundry.js:3262 You are referencing DocumentSheet#entity which has been deprecated in favor of DocumentSheet#document

get entity @ foundry.js:3262

foundry.js:2032

**Comment by cr45hmurphy** [comment] 2021-06-06 22:19
I'm running into the same issue. The only work around I have found so far is to type everything into Notepad++ and copy/paste it into the description text boxes. It seems to work once I click "Save". 

If I do not do this, the quest simply disappears, though it CAN be found within the Quest Log folder.

**Comment by xdy** [comment] 2021-06-07 20:30
@happydevil37 This looks a bit like it's a problem with a module (probably image-hover), try if it works with no modules enabled. If that works, I suggest using https://foundryvtt.com/packages/find-the-culprit/ to figure out which module there is a conflict with.
If image-hover is the problem module, try setting image-hover to only show the image if you click a key while you hover.

@cr45hmurphy That suggests that the problem is with any kind of rich text (i.e. taken from word, a pdf, etc, that has any form of formatting). I tend to write plain text into the quest description rather than pasting in from other programs, which is probably why it's only happened once for me. (Possibly due to me pasting in text from elsewhere, though I'm not sure.)

**Comment by cr45hmurphy** [comment] 2021-06-07 21:22
> @cr45hmurphy That suggests that the problem is with any kind of rich text (i.e. taken from word, a pdf, etc, that has any form of formatting). I tend to write plain text into the quest description rather than pasting in from other programs, which is probably why it's only happened once for me. (Possibly due to me pasting in text from elsewhere, though I'm not sure.)

I would tend to agree. However, in this case, merely typing information directly into the Quest Description box is enough to cause the issue to occur. I actually have to type it into the box, copy/paste it into Notepad++, and copy/paste it back into the box for it to work.

**Comment by happydevil37** [comment] 2021-06-07 21:54
Ok, I have narrowed it down to 1 particular world. Just happens to be the one we are playing at the moment…

 

It’s a PF1 world and I created a new one and tested it and it works – find the culprit said it was Forian’s quest log itself… but why that one world, it’s a standard PF1 world – nothing is different from any of my other worlds…. 

 

I guess the only option is to try and export everything from that world into a new one

**Comment by typhonrt** [comment] 2021-06-10 11:06
While I can't help w/ old quest data... I have a PR which fixes this issue and allows rich text and all sorts of fancy markup to be entered into quest fields.. 

https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/45

**Comment by xdy** [comment] 2021-06-10 17:53
Closing as duplicate of #32

**Closed by xdy** 2021-06-10 17:53 UTC
Labels: bug
