### ISSUE TITLE
[BUG] Objectives/rewards set as hidden are showing to the players.

### ISSUE THREAD

**Issue by guifa11** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#5] opened 2020-12-17 21:27 UTC
**Module Version:** v0.0.0

**Describe the bug**
The rewards and objectives that are set as hidden are showing to the players.

**To Reproduce**
1. Make a quest
2. ADD some objective
3. Set then as hidden
4. Players will still see the objectives (the hidden and unhidden)

**Expected behavior**
Hidden objectives should not appear to players

**Screenshots**
https://i.imgur.com/grXqyaw.png

**Browser:**
Chrome

**Foundry Version:** 0.7.8

**Game System:** 1.2.0

**Additional context**
Those are the modules that i use:
"Plutonium v1.16.2", "Quick Insert - Search Widget v2.4.0", "FPS Meter v1.0.1", "Cautious Gamemaster's Pack v0.1.6", "Show Drag Distance v2.2.3", "Autocomplete Whisper v0.3.2", "Chat Portrait v0.2.1", "Combat Enhancements v0.1.3", "Illandril's Chat Enhancements v1.0.3", "Polyglot v1.4.0", "Token Action HUD v0.10.11", "Token Info Icons v2.1.3", "Zoom/Pan Options v1.4.0", "Background Volume v1.1.2", "Show Notes v0.3", "FXMaster v0.9.9", "GM Notes v0.3", "Torch v1.1.4", "Tidy5e Sheet v0.3.7", "Loot Sheet NPC 5e v2.2.2", "Token HUD Wildcard v1.2.0", "SoundBoard by Blitz v1.1.10", "Bellows v0.3.2", "Forien's Copy Environment v1.1.1", "Dancing Lights by Blitz v2.1.5", "Multilevel Tokens v1.3.4", "OneJournal v1.4.1", "QuickSceneView v0.0.2", "Stat Drawer v0.2", "Combat Utility Belt v1.3.8", "Dynamic Active Effects SRD v4.0.2", "Dynamic effects using Active Effects v0.2.29", "Easy Target v2.7", "Let Me Roll That For You! v1.5", "Midi QOL v0.3.39", "Tidy UI - Game Settings v0.1.21", "About Time v0.1.60", "The Furnace v2.6.0", "Foundry Community Macros v0.30", "Forien's Quest Log v0.5.3", "Calendar/Weather v3.1.1", "Compendium Folders v2.1.4", "Macro Folders v1.0.7", "Better Curses v2.1.0", "MiWwewa's Free Maps Bundle v1.3.0", "Dr. Mapzo free maps (unofficial) v0.17.0", "The MAD Cartographer | Free Battlemap Pack v1.0.1", "Foundry Community Tables v0.11", "Better Roll Tables v1.6.4", "Find the culprit v1.3.3"

I tried without any module except FQL but the bug still happens.

**Comment by jamescosta** [comment] 2020-12-28 20:17
Just to add here, this seems to also be happening on Foundry 0.7.9 (with DnD Game System 1.2.0).

**Comment by Kayne** [comment] 2021-02-12 16:29
In #10 I commented with a work around, for time being. Also, #10 duplicates this, so I figure one issue is enough.

**Comment by anthonyronda** [comment] 2021-06-12 19:41
@guifa11 I'm closing this as working as intended (see Kayne's reply). I'll ask a group of contributors if they'd like to add this as an enhancement

**Closed** 2021-06-12 19:41 UTC
Labels: bug, wontfix
