### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adacosta92** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#39] opened 2021-06-02 15:37 UTC
**Module Version:** v0.5.8

**Describe the bug**

**To Reproduce**
1. Create a quest. 
2. add a 2x8 Table in the quest description
3. Save the description. it should be fine
4. edit the quest description and move the column divider to the left/right, save the quest.

Alternatively, adding specific items as rewards seem to trigger the error as well. Deleting the item/rewards from the _fql_ folder journalEntry does not fix it.

**Expected behavior**
The console displays the errors (or similar):
```
Forien's Quest Log | Quest Folder contains invalid entry. The "Test2" is either corrupted Quest Entry, or non-Quest Journal Entry.
quest.mjs:408 SyntaxError: Unexpected token \ in JSON at position 147
    at JSON.parse (<anonymous>)
    at Function.getContent (quest.mjs:404)
    at Function.get (quest.mjs:264)
    at new QuestPreview (quest-preview.mjs:15)
    at HTMLDivElement.<anonymous> (quest-log.mjs:99)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)
getContent @ quest.mjs:408
get @ quest.mjs:264
QuestPreview @ quest-preview.mjs:15
(anonymous) @ quest-log.mjs:99
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
quest.mjs:265 Uncaught TypeError: Cannot set property 'permission' of null
    at Function.get (quest.mjs:265)
    at new QuestPreview (quest-preview.mjs:15)
    at HTMLDivElement.<anonymous> (quest-log.mjs:99)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)
get @ quest.mjs:265
QuestPreview @ quest-preview.mjs:15
(anonymous) @ quest-log.mjs:99
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
``` 

**Screenshots**
![chrome_Q51CJGOM5g](https://user-images.githubusercontent.com/67127175/120509255-585e0700-c396-11eb-9bfe-214358adceaf.png)

**Browser:**
 - Chrome or Electron

**Foundry Version:** 
0.7.9, 0.7.10

**Game System:** 
dnd5e

**Additional context**
Happens with NO other modules installed.

**Comment by xdy** [comment] 2021-06-04 02:28
As noted in a comment on #32 the reason is that pasting from the browser contains \n characters (and possibly other problematic characters), which makes the json parsing fail. See comments on #32 or #40 for a possible workaround.
Closing this as duplicate of #32

**Closed by xdy** 2021-06-04 02:28 UTC
Labels: bug
